In [1]:
import numpy as np #importing numpy library as np
my_list=[1,2,3,4] #declares a list
my_list

[1, 2, 3, 4]

In [2]:
#converting list to array
arr=np.array(my_list)
arr

array([1, 2, 3, 4])

In [3]:
#the arange works like the range in for loop i.e it generates an array for the range we give i.e the start point , the end point
#and the increment or decrement 
np.arange(0,10)#an array from 0 to 9 with increment of 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#creating multi dimensional array
a=np.array([[1,2,3,],[3,4,5],[5,6,7],[7,8,9]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [5]:
a[:3]#displays rows 0 ,1 , 2 

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [6]:
#randomly shuffling value locations
li=[4,6,3,9,1]
np.random.shuffle(li)#shuffles the list randomly
print(li)

[1, 4, 3, 9, 6]


In [7]:
np.arange(0,11,2)#gives an array witht the specified range and increment

array([ 0,  2,  4,  6,  8, 10])

In [8]:
#the zeroes function 
#generates an array with entries 0.
np.zeros(5)#where 5 is the size

array([0., 0., 0., 0., 0.])

In [9]:
#the ones function 
#generates an array with entries 1.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros((3,5))#3 rows and  5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#generating random value between 1 and 100
np.random.randint(0,100)

28

In [13]:
#generating a multi dimensional array defining its size by generating random values between 0 and 1000
np.random.randint(0,1000,(4,4))

array([[677, 704, 579, 877],
       [317, 663, 360, 514],
       [380, 922, 731, 718],
       [972, 313, 723, 581]])

In [15]:
#generating a one dimensional array of size 6 by generating random values between 0 and 100
np.random.randint(0,100,6)

array([81, 91, 42, 29,  1, 85])

In [17]:
#fixing a randomly generated array using seed i,e on refreshing or re running the value of the array does not change
np.random.seed(1)#we have assigned the value of the random array generated below to 1 
#we can pass any number and then even if we rerun or refresh the value of array in 1 stays same 
#using this method we can also assign the value of the array to a particular variable
np.random.randint(0,100,10)

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [19]:
np.random.seed(10)
arr=np.random.randint(0,100,10)
print(arr)

[ 9 15 64 28 89 93 29  8 73  0]


In [20]:
arr.max()#gives the maximum value in array

93

In [21]:
arr.min()#gives the minimum value in array

0

In [22]:
arr.mean()#gives the mean of all the elements in the array

40.8

In [23]:
arr.argmax()#gives the index at which the maximum value is present in an array

5

In [24]:
arr.reshape(2,5)#shapes the array to a multi dimensional array of 2 rows and 5 columns

array([[ 9, 15, 64, 28, 89],
       [93, 29,  8, 73,  0]])

In [26]:
mat=np.arange(0,100).reshape(10,10)
mat #values in array go from 0 to 100 and have been shaped into a multi dimensional array of 10 rows and 10 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mat[0:5]#displays rows from 0 to 4 index

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
mat[0,:]#shows all the values in the zeroeth row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
mat[:,0]#shows all the values in the 0th column

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
mat[0:3,0:3]#displays rows from 0 to 2 and columns also from 0 to 2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [32]:
a=np.array([1,2,3,4,5,6])
b=np.array([6,6,4,3,3,2])
print(a)
print(b)

[1 2 3 4 5 6]
[6 6 4 3 3 2]


In [33]:
#adding two arrays
a+b

array([7, 8, 7, 7, 8, 8])

In [34]:
#adding a particular value to all the elements of an array
a+100

array([101, 102, 103, 104, 105, 106])

In [35]:
#multiplication of two arrays
a*b

array([ 6, 12, 12, 12, 15, 12])

In [36]:
#multiplying a particular value to all the elements of an array
a*100

array([100, 200, 300, 400, 500, 600])

In [37]:
#subtraction of two arrays
a-b

array([-5, -4, -1,  1,  2,  4])

In [39]:
#using append to add value to an array
c=np.append(a,[9,0,8])
c

array([1, 2, 3, 4, 5, 6, 9, 0, 8])

In [40]:
d=np.append(a,[4])
d

array([1, 2, 3, 4, 5, 6, 4])

In [41]:
#deleting value from a particular index
e=np.delete(a,1)
e

array([1, 3, 4, 5, 6])

In [43]:
#concatenating multiple arrays
f=np.concatenate((a,np.array([3,4])))
f

array([1, 2, 3, 4, 5, 6, 3, 4])

In [44]:
g=np.concatenate((a,np.array([1,2,3]),np.array([90,34])))#concatenating multiple arrays which cannot be done using append
g

array([ 1,  2,  3,  4,  5,  6,  1,  2,  3, 90, 34])

In [45]:
#add function
np.add(a,b)

array([7, 8, 7, 7, 8, 8])

In [46]:
#subtract function
np.subtract(a,b)

array([-5, -4, -1,  1,  2,  4])

In [47]:
#multiply function
np.multiply(a,b)

array([ 6, 12, 12, 12, 15, 12])